"""Payslip PDFs in English or Bangla, rendered with WeasyPrint (HarfBuzz shaping) and fonts
that ship with the app, so Bangla names and conjuncts render the same everywhere."""

from __future__ import annotations

import calendar
from decimal import Decimal
from functools import cache
from html import escape
from pathlib import Path
from typing import Any

from app.modules.payroll import defaults
from app.modules.payroll.schemas import PayslipOut

FONTS = Path(__file__).parent / "fonts"

BN_DIGITS = str.maketrans("0123456789", "০১২৩৪৫৬৭৮৯")
BN_MONTHS = [
    "জানুয়ারি",
    "ফেব্রুয়ারি",
    "মার্চ",
    "এপ্রিল",
    "মে",
    "জুন",
    "জুলাই",
    "আগস্ট",
    "সেপ্টেম্বর",
    "অক্টোবর",
    "নভেম্বর",
    "ডিসেম্বর",
]
SYMBOLS = {"BDT": "৳", "INR": "₹", "USD": "$", "EUR": "€", "GBP": "£", "PKR": "Rs", "NPR": "Rs", "LKR": "Rs"}
# Currencies written with lakh grouping (1,23,45,678).
LAKH = {"BDT", "INR", "NPR", "PKR"}

DASH = "\u2013"

TEXT = {
    "en": {
        "payslip": "Payslip",
        "employee": "Employee",
        "code": "Code",
        "department": "Department",
        "title": "Job title",
        "paid_by": "Paid by",
        "cash": "Cash",
        "bank": "Bank",
        "wallet": "Mobile wallet",
        "days": "Days in month",
        "payable": "Days paid",
        "unpaid": "Unpaid leave days",
        "hours": "Hours worked",
        "overtime": "Overtime hours",
        "earnings": "Earnings",
        "deductions": "Deductions",
        "gross": "Total earnings",
        "total_deductions": "Total deductions",
        "net": "Net pay",
        "carried": "Carried to next month as an advance",
        "none": "None",
        "footer": "Generated by CompanyMgmt. This payslip doesn't need a signature.",
    },
    "bn": {
        "payslip": "বেতন বিবরণী",
        "employee": "কর্মী",
        "code": "কোড",
        "department": "বিভাগ",
        "title": "পদবি",
        "paid_by": "পরিশোধের মাধ্যম",
        "cash": "নগদ",
        "bank": "ব্যাংক",
        "wallet": "মোবাইল ওয়ালেট",
        "days": "মাসের দিন",
        "payable": "বেতনযোগ্য দিন",
        "unpaid": "বিনা বেতনে ছুটির দিন",
        "hours": "কাজের ঘণ্টা",
        "overtime": "ওভারটাইম ঘণ্টা",
        "earnings": "আয়",
        "deductions": "কর্তন",
        "gross": "মোট আয়",
        "total_deductions": "মোট কর্তন",
        "net": "নিট বেতন",
        "carried": "অগ্রিম হিসেবে পরের মাসে যাবে",
        "none": "নেই",
        "footer": "CompanyMgmt দ্বারা তৈরি। এই বেতন বিবরণীতে স্বাক্ষরের প্রয়োজন নেই।",
    },
}

LINE_LABELS_BN = {
    "basic": "মূল বেতন",
    "house_rent": "বাড়ি ভাড়া",
    "medical": "চিকিৎসা ভাতা",
    "conveyance": "যাতায়াত ভাতা",
    "other": "অন্যান্য ভাতা",
    "hours": "কাজের ঘণ্টা",
    "days": "কাজের দিন",
    "overtime": "ওভারটাইম",
    "unpaid_leave": "বিনা বেতনে ছুটি",
    "tax": "আয়কর",
    "rounding": "রাউন্ডিং সমন্বয়",
}


def _group(whole: int, lakh: bool) -> str:
    digits = str(whole)
    if not lakh or len(digits) <= 3:
        return f"{whole:,}"
    head, tail = digits[:-3], digits[-3:]
    parts: list[str] = []
    while len(head) > 2:
        parts.insert(0, head[-2:])
        head = head[:-2]
    if head:
        parts.insert(0, head)
    return ",".join([*parts, tail])


def amount(minor: int, currency: str, lang: str) -> str:
    unit = defaults.unit_for(currency)
    sign = "-" if minor < 0 else ""
    whole, cents = divmod(abs(minor), unit)
    text = _group(whole, currency in LAKH)
    if unit > 1 and cents:
        text += f".{cents:02d}"
    symbol = SYMBOLS.get(currency, currency + " ")
    out = f"{sign}{symbol}{text}"
    return out.translate(BN_DIGITS) if lang == "bn" else out


def number(value: float | Decimal | int, lang: str) -> str:
    text = f"{Decimal(str(value)).normalize():f}"
    return text.translate(BN_DIGITS) if lang == "bn" else text


def month_name(period: str, lang: str) -> str:
    year, month = int(period[:4]), int(period[5:])
    if lang == "bn":
        return f"{BN_MONTHS[month - 1]} {str(year).translate(BN_DIGITS)}"
    return f"{calendar.month_name[month]} {year}"


@cache
def _css() -> str:
    faces = "\n".join(
        f"""@font-face {{ font-family: "{family}"; font-weight: {weight};
              src: url("{(FONTS / file).as_uri()}"); }}"""
        for family, weight, file in (
            ("IBM Plex Sans", 400, "IBMPlexSans-Regular.ttf"),
            ("IBM Plex Sans", 600, "IBMPlexSans-SemiBold.ttf"),
            ("Noto Sans Bengali", 400, "NotoSansBengali-Regular.ttf"),
            ("Noto Sans Bengali", 600, "NotoSansBengali-SemiBold.ttf"),
        )
    )
    return (
        faces
        + """
    @page { size: A4; margin: 18mm 16mm; }
    body { font-family: "IBM Plex Sans", "Noto Sans Bengali", sans-serif; font-size: 10pt; color: #16161d; }
    body.bn { line-height: 1.6; }
    header { display: flex; justify-content: space-between; align-items: flex-end;
             border-bottom: 2px solid #6d28d9; padding-bottom: 8pt; margin-bottom: 14pt; }
    .company { font-size: 15pt; font-weight: 600; }
    .doc { text-align: right; }
    .doc .title { font-size: 13pt; font-weight: 600; color: #6d28d9; }
    .muted { color: #5b5b66; }
    dl { display: grid; grid-template-columns: 1fr 1fr; gap: 4pt 24pt; margin: 0 0 14pt; }
    dl div { display: flex; justify-content: space-between; padding: 3pt 0;
             border-bottom: 0.5pt solid #e4e4e7; }
    dt { color: #5b5b66; } dd { margin: 0; font-weight: 600; }
    .cols { display: flex; gap: 18pt; }
    .cols section { flex: 1; }
    h2 { font-size: 10.5pt; margin: 0 0 4pt; }
    table { width: 100%; border-collapse: collapse; }
    td { padding: 4pt 0; border-bottom: 0.5pt solid #e4e4e7; }
    td.amt { text-align: right; white-space: nowrap; }
    tr.total td { font-weight: 600; border-bottom: none; border-top: 1pt solid #16161d; }
    .net { margin-top: 16pt; padding: 10pt 12pt; background: #f3effd; border-radius: 6pt;
           display: flex; justify-content: space-between; font-size: 13pt; font-weight: 600; }
    .note { margin-top: 6pt; color: #9a3412; }
    footer { margin-top: 24pt; font-size: 8pt; color: #5b5b66; }
    """
    )


def render_html(slip: PayslipOut, *, company: str, lang: str) -> str:
    t = TEXT[lang]
    currency = slip.currency or "BDT"
    e = escape

    def label(line_code: str, english: str) -> str:
        return LINE_LABELS_BN.get(line_code, english) if lang == "bn" else english

    def rows(kind: str) -> str:
        items = [x for x in slip.lines if x.kind == kind]
        if not items:
            return f'<tr><td class="muted">{t["none"]}</td><td></td></tr>'
        return "".join(
            f"<tr><td>{e(label(x.code, x.label))}</td>"
            f'<td class="amt">{amount(x.amount, currency, lang)}</td></tr>'
            for x in items
        )

    method = t.get(slip.payment_method, slip.payment_method)
    if slip.provider:
        method = f"{method} · {slip.provider}"
    if slip.account_last4:
        method += f" ··{slip.account_last4}"
    facts = [
        (t["employee"], slip.employee_name),
        (t["code"], slip.employee_code or DASH),
        (t["department"], slip.department_name or DASH),
        (t["title"], slip.job_title or DASH),
        (t["paid_by"], method),
        (t["days"], number(slip.days_in_period, lang)),
        (t["payable"], number(slip.payable_days, lang)),
        (t["unpaid"], number(slip.unpaid_leave_days, lang)),
        (t["hours"], number(round(slip.worked_minutes / 60, 1), lang)),
        (t["overtime"], number(round(slip.overtime_minutes / 60, 1), lang)),
    ]
    fact_html = "".join(f"<div><dt>{e(k)}</dt><dd>{e(str(v))}</dd></div>" for k, v in facts)
    carried = (
        f'<p class="note">{amount(slip.carried_forward, currency, lang)} · {t["carried"]}</p>'
        if slip.carried_forward
        else ""
    )
    return f"""<!doctype html>
<html lang="{lang}"><head><meta charset="utf-8"><style>{_css()}</style></head>
<body class="{lang}">
<header>
  <div class="company">{e(company)}</div>
  <div class="doc"><div class="title">{t["payslip"]}</div>
  <div class="muted">{e(month_name(slip.period or "2000-01", lang))}</div></div>
</header>
<dl>{fact_html}</dl>
<div class="cols">
  <section><h2>{t["earnings"]}</h2><table>{rows("earning")}
    <tr class="total"><td>{t["gross"]}</td>
    <td class="amt">{amount(slip.gross, currency, lang)}</td></tr></table></section>
  <section><h2>{t["deductions"]}</h2><table>{rows("deduction")}
    <tr class="total"><td>{t["total_deductions"]}</td>
    <td class="amt">{amount(slip.deductions, currency, lang)}</td></tr></table></section>
</div>
<div class="net"><span>{t["net"]}</span><span>{amount(slip.net, currency, lang)}</span></div>
{carried}
<footer>{t["footer"]}</footer>
</body></html>"""


@cache
def _fetcher() -> Any:
    """Loads only the bundled fonts: never the network or any other file."""
    from weasyprint.urls import URLFetcher, URLFetchingError

    allowed = frozenset((FONTS / f).as_uri() for f in FONTS.iterdir() if f.suffix == ".ttf")

    class FontsOnly(URLFetcher):  # type: ignore[misc]
        def fetch(self, url: str, headers: Any = None) -> Any:
            if url not in allowed:
                raise URLFetchingError(f"Blocked resource: {url[:80]}")
            return super().fetch(url, headers)

    return FontsOnly(allowed_protocols=("file",))


def render_pdf(slip: PayslipOut, *, company: str, lang: str) -> bytes:
    from weasyprint import HTML  # imported here: it loads native libraries

    html = HTML(string=render_html(slip, company=company, lang=lang), url_fetcher=_fetcher())
    pdf: bytes = html.write_pdf()
    return pdf
