"""announcements: posts to everyone, branches or departments, with read receipts

Revision ID: 0010
Revises: 0009
Create Date: 2026-10-01 07:39:51.012593
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from migrations import rls

revision: str = "0010"
down_revision: str | None = "0009"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "announcements",
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("audience", sa.String(length=12), nullable=False),
        sa.Column("audience_ids", postgresql.ARRAY(sa.Uuid()), nullable=False),
        sa.Column("pinned", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("author_id", sa.Uuid(), nullable=True),
        sa.Column("edited_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "audience = 'everyone' OR cardinality(audience_ids) > 0",
            name=op.f("ck_announcements_audience_ids"),
        ),
        sa.CheckConstraint(
            "audience IN ('everyone', 'branches', 'departments')", name=op.f("ck_announcements_audience")
        ),
        sa.ForeignKeyConstraint(["author_id"], ["users.id"], name=op.f("fk_announcements_author_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_announcements")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_announcements_tenant_id_id")),
    )
    op.create_index("ix_announcements_feed", "announcements", ["tenant_id", "published_at"], unique=False)
    op.create_index(op.f("ix_announcements_tenant_id"), "announcements", ["tenant_id"], unique=False)
    op.create_table(
        "announcement_reads",
        sa.Column("announcement_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "announcement_id"],
            ["announcements.tenant_id", "announcements.id"],
            name=op.f("fk_announcement_reads_tenant_id_announcement_id_announcements"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_announcement_reads_user_id_users")),
        sa.PrimaryKeyConstraint("announcement_id", "user_id", name=op.f("pk_announcement_reads")),
    )
    op.create_index(
        op.f("ix_announcement_reads_tenant_id"), "announcement_reads", ["tenant_id"], unique=False
    )
    # ### end Alembic commands ###
    rls.tenant_table("announcements")
    # Reads are only ever added (and removed with their post).
    rls.tenant_table("announcement_reads", privileges="SELECT, INSERT, DELETE")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_announcement_reads_tenant_id"), table_name="announcement_reads")
    op.drop_table("announcement_reads")
    op.drop_index(op.f("ix_announcements_tenant_id"), table_name="announcements")
    op.drop_index("ix_announcements_feed", table_name="announcements")
    op.drop_table("announcements")
    # ### end Alembic commands ###
