"""shop: catalogue, taxes, cash drawers, sales, customers and dues, expenses

Revision ID: 0020
Revises: 0019
Create Date: 2026-10-04 22:58:00.200592
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from migrations import rls

revision: str = "0020"
down_revision: str | None = "0019"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "customers",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("phone", sa.String(length=40), nullable=True),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("credit_limit", sa.BigInteger(), nullable=True),
        sa.Column("active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_customers")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_customers_tenant_id_id")),
    )
    op.create_index("ix_customers_name", "customers", ["tenant_id", "name"], unique=False)
    op.create_index("ix_customers_phone", "customers", ["tenant_id", "phone"], unique=False)
    op.create_index(op.f("ix_customers_tenant_id"), "customers", ["tenant_id"], unique=False)
    op.create_table(
        "expense_categories",
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("code", sa.String(length=20), nullable=True),
        sa.Column("active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_expense_categories")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_expense_categories_tenant_id_id")),
    )
    op.create_index(
        op.f("ix_expense_categories_tenant_id"), "expense_categories", ["tenant_id"], unique=False
    )
    op.create_table(
        "product_categories",
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("color", sa.String(length=7), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_categories")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_product_categories_tenant_id_id")),
    )
    op.create_index(
        op.f("ix_product_categories_tenant_id"), "product_categories", ["tenant_id"], unique=False
    )
    op.create_table(
        "shop_settings",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("prices_include_tax", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("cash_rounding", sa.Integer(), nullable=False),
        sa.Column("tax_id_label", sa.String(length=40), nullable=True),
        sa.Column("tax_id", sa.String(length=60), nullable=True),
        sa.Column("receipt_header", sa.Text(), nullable=True),
        sa.Column("receipt_footer", sa.Text(), nullable=True),
        sa.Column("next_number", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("tenant_id", name=op.f("pk_shop_settings")),
    )
    op.create_table(
        "tax_rates",
        sa.Column("name", sa.String(length=60), nullable=False),
        sa.Column("code", sa.String(length=20), nullable=True),
        sa.Column("percent", sa.Numeric(precision=7, scale=4), nullable=False),
        sa.Column("compound", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("default", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint("percent >= 0 AND percent <= 100", name=op.f("ck_tax_rates_percent")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tax_rates")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_tax_rates_tenant_id_id")),
    )
    op.create_index(op.f("ix_tax_rates_tenant_id"), "tax_rates", ["tenant_id"], unique=False)
    op.create_table(
        "products",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("code", sa.String(length=40), nullable=True),
        sa.Column("category_id", sa.Uuid(), nullable=True),
        sa.Column("price", sa.BigInteger(), nullable=False),
        sa.Column("tax_rate_ids", postgresql.ARRAY(sa.Uuid()), nullable=False),
        sa.Column("unit", sa.String(length=10), nullable=False),
        sa.Column("favorite", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint("price >= 0", name=op.f("ck_products_price")),
        sa.ForeignKeyConstraint(
            ["tenant_id", "category_id"],
            ["product_categories.tenant_id", "product_categories.id"],
            name=op.f("fk_products_tenant_id_category_id_product_categories"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_products")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_products_tenant_id_id")),
    )
    op.create_index("ix_products_name", "products", ["tenant_id", "name"], unique=False)
    op.create_index(op.f("ix_products_tenant_id"), "products", ["tenant_id"], unique=False)
    op.create_table(
        "cash_sessions",
        sa.Column("branch_id", sa.Uuid(), nullable=True),
        sa.Column("opened_by", sa.Uuid(), nullable=False),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("opening_float", sa.BigInteger(), nullable=False),
        sa.Column("closed_by", sa.Uuid(), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expected_cash", sa.BigInteger(), nullable=True),
        sa.Column("counted_cash", sa.BigInteger(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["closed_by"], ["users.id"], name=op.f("fk_cash_sessions_closed_by_users")),
        sa.ForeignKeyConstraint(["opened_by"], ["users.id"], name=op.f("fk_cash_sessions_opened_by_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cash_sessions")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_cash_sessions_tenant_id_id")),
    )
    op.create_index(op.f("ix_cash_sessions_tenant_id"), "cash_sessions", ["tenant_id"], unique=False)
    op.create_index(
        "uq_cash_sessions_open",
        "cash_sessions",
        ["tenant_id", "opened_by"],
        unique=True,
        postgresql_where=sa.text("closed_at IS NULL"),
    )
    op.create_table(
        "customer_entries",
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=12), nullable=False),
        sa.Column("amount", sa.BigInteger(), nullable=False),
        sa.Column("occurred_on", sa.Date(), nullable=False),
        sa.Column("sale_id", sa.Uuid(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "kind IN ('sale', 'return', 'payment', 'adjustment')", name=op.f("ck_customer_entries_kind")
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_customer_entries_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "customer_id"],
            ["customers.tenant_id", "customers.id"],
            name=op.f("fk_customer_entries_tenant_id_customer_id_customers"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_customer_entries")),
    )
    op.create_index(
        "ix_customer_entries_customer",
        "customer_entries",
        ["tenant_id", "customer_id", "occurred_on"],
        unique=False,
    )
    op.create_index(op.f("ix_customer_entries_tenant_id"), "customer_entries", ["tenant_id"], unique=False)
    op.create_table(
        "expenses",
        sa.Column("kind", sa.String(length=10), nullable=False),
        sa.Column("occurred_on", sa.Date(), nullable=False),
        sa.Column("amount", sa.BigInteger(), nullable=False),
        sa.Column("category_id", sa.Uuid(), nullable=True),
        sa.Column("payee", sa.String(length=120), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("paid_from", sa.String(length=12), nullable=False),
        sa.Column("branch_id", sa.Uuid(), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("receipt_name", sa.String(length=200), nullable=True),
        sa.Column("receipt_type", sa.String(length=100), nullable=True),
        sa.Column("receipt", sa.LargeBinary(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint("kind IN ('expense', 'top_up')", name=op.f("ck_expenses_kind")),
        sa.CheckConstraint(
            "paid_from IN ('drawer', 'petty_cash', 'bank', 'other')", name=op.f("ck_expenses_paid_from")
        ),
        sa.CheckConstraint("amount > 0", name=op.f("ck_expenses_amount")),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], name=op.f("fk_expenses_created_by_users")),
        sa.ForeignKeyConstraint(
            ["tenant_id", "category_id"],
            ["expense_categories.tenant_id", "expense_categories.id"],
            name=op.f("fk_expenses_tenant_id_category_id_expense_categories"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_expenses")),
    )
    op.create_index("ix_expenses_day", "expenses", ["tenant_id", "occurred_on"], unique=False)
    op.create_index(op.f("ix_expenses_tenant_id"), "expenses", ["tenant_id"], unique=False)
    op.create_table(
        "sales",
        sa.Column("number", sa.BigInteger(), nullable=False),
        sa.Column("client_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=10), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("original_id", sa.Uuid(), nullable=True),
        sa.Column("session_id", sa.Uuid(), nullable=True),
        sa.Column("branch_id", sa.Uuid(), nullable=True),
        sa.Column("sold_by", sa.Uuid(), nullable=False),
        sa.Column("sold_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=True),
        sa.Column("net", sa.BigInteger(), nullable=False),
        sa.Column("tax", sa.BigInteger(), nullable=False),
        sa.Column("rounding", sa.BigInteger(), nullable=False),
        sa.Column("total", sa.BigInteger(), nullable=False),
        sa.Column("paid_cash", sa.BigInteger(), nullable=False),
        sa.Column("change", sa.BigInteger(), nullable=False),
        sa.Column("on_account", sa.BigInteger(), nullable=False),
        sa.Column("prices_include_tax", sa.Boolean(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("voided_by", sa.Uuid(), nullable=True),
        sa.Column("voided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("void_reason", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("kind IN ('sale', 'return')", name=op.f("ck_sales_kind")),
        sa.CheckConstraint("status IN ('completed', 'voided')", name=op.f("ck_sales_status")),
        sa.ForeignKeyConstraint(["sold_by"], ["users.id"], name=op.f("fk_sales_sold_by_users")),
        sa.ForeignKeyConstraint(
            ["tenant_id", "original_id"],
            ["sales.tenant_id", "sales.id"],
            name=op.f("fk_sales_tenant_id_original_id_sales"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "session_id"],
            ["cash_sessions.tenant_id", "cash_sessions.id"],
            name=op.f("fk_sales_tenant_id_session_id_cash_sessions"),
        ),
        sa.ForeignKeyConstraint(["voided_by"], ["users.id"], name=op.f("fk_sales_voided_by_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sales")),
        sa.UniqueConstraint("tenant_id", "client_id", name=op.f("uq_sales_tenant_id_client_id")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_sales_tenant_id_id")),
        sa.UniqueConstraint("tenant_id", "number", name=op.f("uq_sales_tenant_id_number")),
    )
    op.create_index(op.f("ix_sales_tenant_id"), "sales", ["tenant_id"], unique=False)
    op.create_index("ix_sales_time", "sales", ["tenant_id", "sold_at"], unique=False)
    op.create_table(
        "sale_lines",
        sa.Column("sale_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=12, scale=3), nullable=False),
        sa.Column("unit_price", sa.BigInteger(), nullable=False),
        sa.Column("discount", sa.BigInteger(), nullable=False),
        sa.Column("net", sa.BigInteger(), nullable=False),
        sa.Column("tax", sa.BigInteger(), nullable=False),
        sa.Column("total", sa.BigInteger(), nullable=False),
        sa.Column("taxes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("returned_line_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "sale_id"],
            ["sales.tenant_id", "sales.id"],
            name=op.f("fk_sale_lines_tenant_id_sale_id_sales"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sale_lines")),
    )
    op.create_index("ix_sale_lines_sale", "sale_lines", ["tenant_id", "sale_id"], unique=False)
    op.create_index(op.f("ix_sale_lines_tenant_id"), "sale_lines", ["tenant_id"], unique=False)
    rls.tenant_table("customers")
    rls.tenant_table("expense_categories")
    rls.tenant_table("product_categories")
    rls.tenant_table("shop_settings")
    rls.tenant_table("tax_rates")
    rls.tenant_table("products")
    rls.tenant_table("cash_sessions")
    rls.tenant_table("customer_entries")
    rls.tenant_table("expenses")
    rls.tenant_table("sales")
    rls.tenant_table("sale_lines")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sale_lines_tenant_id"), table_name="sale_lines")
    op.drop_index("ix_sale_lines_sale", table_name="sale_lines")
    op.drop_table("sale_lines")
    op.drop_index("ix_sales_time", table_name="sales")
    op.drop_index(op.f("ix_sales_tenant_id"), table_name="sales")
    op.drop_table("sales")
    op.drop_index(op.f("ix_expenses_tenant_id"), table_name="expenses")
    op.drop_index("ix_expenses_day", table_name="expenses")
    op.drop_table("expenses")
    op.drop_index(op.f("ix_customer_entries_tenant_id"), table_name="customer_entries")
    op.drop_index("ix_customer_entries_customer", table_name="customer_entries")
    op.drop_table("customer_entries")
    op.drop_index(
        "uq_cash_sessions_open", table_name="cash_sessions", postgresql_where=sa.text("closed_at IS NULL")
    )
    op.drop_index(op.f("ix_cash_sessions_tenant_id"), table_name="cash_sessions")
    op.drop_table("cash_sessions")
    op.drop_index(op.f("ix_products_tenant_id"), table_name="products")
    op.drop_index("ix_products_name", table_name="products")
    op.drop_table("products")
    op.drop_index(op.f("ix_tax_rates_tenant_id"), table_name="tax_rates")
    op.drop_table("tax_rates")
    op.drop_table("shop_settings")
    op.drop_index(op.f("ix_product_categories_tenant_id"), table_name="product_categories")
    op.drop_table("product_categories")
    op.drop_index(op.f("ix_expense_categories_tenant_id"), table_name="expense_categories")
    op.drop_table("expense_categories")
    op.drop_index(op.f("ix_customers_tenant_id"), table_name="customers")
    op.drop_index("ix_customers_phone", table_name="customers")
    op.drop_index("ix_customers_name", table_name="customers")
    op.drop_table("customers")
    # ### end Alembic commands ###
