"""location-based attendance

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-30 16:35:05.362204
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from migrations import rls

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "attendance_settings",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("location_mode", sa.String(length=10), nullable=False),
        sa.Column("max_accuracy_m", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "location_mode IN ('off', 'record', 'require')", name=op.f("ck_attendance_settings_location_mode")
        ),
        sa.CheckConstraint(
            "max_accuracy_m BETWEEN 10 AND 1000", name=op.f("ck_attendance_settings_max_accuracy")
        ),
        sa.PrimaryKeyConstraint("tenant_id", name=op.f("pk_attendance_settings")),
    )
    op.add_column(
        "attendance_records", sa.Column("in_latitude", sa.Numeric(precision=7, scale=4), nullable=True)
    )
    op.add_column(
        "attendance_records", sa.Column("in_longitude", sa.Numeric(precision=8, scale=4), nullable=True)
    )
    op.add_column("attendance_records", sa.Column("in_accuracy_m", sa.Integer(), nullable=True))
    op.add_column("attendance_records", sa.Column("in_distance_m", sa.Integer(), nullable=True))
    op.add_column("attendance_records", sa.Column("in_geo", sa.String(length=8), nullable=True))
    op.add_column(
        "attendance_records", sa.Column("out_latitude", sa.Numeric(precision=7, scale=4), nullable=True)
    )
    op.add_column(
        "attendance_records", sa.Column("out_longitude", sa.Numeric(precision=8, scale=4), nullable=True)
    )
    op.add_column("attendance_records", sa.Column("out_accuracy_m", sa.Integer(), nullable=True))
    op.add_column("attendance_records", sa.Column("out_distance_m", sa.Integer(), nullable=True))
    op.add_column("attendance_records", sa.Column("out_geo", sa.String(length=8), nullable=True))
    op.add_column("branches", sa.Column("latitude", sa.Numeric(precision=9, scale=6), nullable=True))
    op.add_column("branches", sa.Column("longitude", sa.Numeric(precision=9, scale=6), nullable=True))
    op.add_column("branches", sa.Column("geofence_m", sa.Integer(), server_default="150", nullable=False))
    # ### end Alembic commands ###
    op.create_check_constraint(
        op.f("ck_branches_location_pair"), "branches", "(latitude IS NULL) = (longitude IS NULL)"
    )
    op.create_check_constraint(
        op.f("ck_branches_latitude"), "branches", "latitude IS NULL OR latitude BETWEEN -90 AND 90"
    )
    op.create_check_constraint(
        op.f("ck_branches_longitude"), "branches", "longitude IS NULL OR longitude BETWEEN -180 AND 180"
    )
    op.create_check_constraint(op.f("ck_branches_geofence"), "branches", "geofence_m BETWEEN 25 AND 5000")
    for prefix in ("in", "out"):
        op.create_check_constraint(
            op.f(f"ck_attendance_records_{prefix}_geo"),
            "attendance_records",
            f"{prefix}_geo IS NULL OR {prefix}_geo IN ('inside', 'outside', 'no_fix', 'no_site')",
        )
    rls.tenant_table("attendance_settings")


def downgrade() -> None:
    for prefix in ("in", "out"):
        op.drop_constraint(op.f(f"ck_attendance_records_{prefix}_geo"), "attendance_records", type_="check")
    for name in ("location_pair", "latitude", "longitude", "geofence"):
        op.drop_constraint(op.f(f"ck_branches_{name}"), "branches", type_="check")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("branches", "geofence_m")
    op.drop_column("branches", "longitude")
    op.drop_column("branches", "latitude")
    op.drop_column("attendance_records", "out_geo")
    op.drop_column("attendance_records", "out_distance_m")
    op.drop_column("attendance_records", "out_accuracy_m")
    op.drop_column("attendance_records", "out_longitude")
    op.drop_column("attendance_records", "out_latitude")
    op.drop_column("attendance_records", "in_geo")
    op.drop_column("attendance_records", "in_distance_m")
    op.drop_column("attendance_records", "in_accuracy_m")
    op.drop_column("attendance_records", "in_longitude")
    op.drop_column("attendance_records", "in_latitude")
    op.drop_table("attendance_settings")
    # ### end Alembic commands ###
