"""sso, own ai key, session method

Revision ID: 0024
Revises: 0023
Create Date: 2026-10-04 23:45:03.815806
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from migrations import rls

revision: str = "0024"
down_revision: str | None = "0023"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sso_connections",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("issuer", sa.String(length=300), nullable=False),
        sa.Column("client_id", sa.String(length=300), nullable=False),
        sa.Column("client_secret_enc", sa.String(length=800), nullable=False),
        sa.Column("domains", sa.ARRAY(sa.String(length=253)), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("auto_join", sa.Boolean(), nullable=False),
        sa.Column("default_role_id", sa.Uuid(), nullable=True),
        sa.Column("provider", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("provider_fetched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("tenant_id", name=op.f("pk_sso_connections")),
    )
    op.create_table(
        "sso_states",
        sa.Column("state_hash", sa.String(length=64), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("nonce", sa.String(length=64), nullable=False),
        sa.Column("verifier", sa.String(length=128), nullable=False),
        sa.Column("next_path", sa.String(length=200), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_sso_states_tenant_id_tenants"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("state_hash", name=op.f("pk_sso_states")),
    )
    op.add_column("ai_settings", sa.Column("own_key_enc", sa.String(length=600), nullable=True))
    op.add_column("ai_settings", sa.Column("own_key_hint", sa.String(length=8), nullable=True))
    op.add_column(
        "auth_sessions", sa.Column("method", sa.String(length=10), server_default="password", nullable=False)
    )
    op.add_column("tenants", sa.Column("sso_enforced", sa.Boolean(), server_default="false", nullable=False))
    rls.tenant_table("sso_connections")
    rls.global_table("sso_states")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tenants", "sso_enforced")
    op.drop_column("auth_sessions", "method")
    op.drop_column("ai_settings", "own_key_hint")
    op.drop_column("ai_settings", "own_key_enc")
    op.drop_table("sso_states")
    op.drop_table("sso_connections")
    # ### end Alembic commands ###
