"""domain events: an append-only log of what happens in each workspace

Revision ID: 0006
Revises: 0005
Create Date: 2026-10-01 02:36:33.333660
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from migrations import rls

revision: str = "0006"
down_revision: str | None = "0005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "domain_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actor_user_id", sa.Uuid(), nullable=True),
        sa.Column("subject_type", sa.String(length=40), nullable=True),
        sa.Column("subject_id", sa.String(length=64), nullable=True),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_domain_events")),
    )
    op.create_index(op.f("ix_domain_events_name"), "domain_events", ["name"], unique=False)
    op.create_index(op.f("ix_domain_events_tenant_id"), "domain_events", ["tenant_id"], unique=False)
    op.create_index("ix_domain_events_time", "domain_events", ["tenant_id", "occurred_at"], unique=False)
    # ### end Alembic commands ###
    rls.tenant_table("domain_events", privileges="SELECT, INSERT")
    rls.append_only("domain_events")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_domain_events_time", table_name="domain_events")
    op.drop_index(op.f("ix_domain_events_tenant_id"), table_name="domain_events")
    op.drop_index(op.f("ix_domain_events_name"), table_name="domain_events")
    op.drop_table("domain_events")
    # ### end Alembic commands ###
