"""leave: types, work week, holidays, requests and balance adjustments

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-30 21:08:46.725336
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from migrations import rls

revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "leave_policies",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("weekly_off", sa.ARRAY(sa.SmallInteger()), nullable=False),
        sa.Column("team_calendar", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "weekly_off <@ ARRAY[1,2,3,4,5,6,7]::smallint[]", name=op.f("ck_leave_policies_weekly_off")
        ),
        sa.PrimaryKeyConstraint("tenant_id", name=op.f("pk_leave_policies")),
    )
    op.create_table(
        "leave_types",
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("paid", sa.Boolean(), nullable=False),
        sa.Column("days_per_year", sa.Numeric(precision=6, scale=1), nullable=True),
        sa.Column("accrual", sa.String(length=10), nullable=False),
        sa.Column("carry_over_max", sa.Numeric(precision=6, scale=1), nullable=False),
        sa.Column("allow_half_day", sa.Boolean(), nullable=False),
        sa.Column("calendar_days", sa.Boolean(), nullable=False),
        sa.Column("prorate", sa.Boolean(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("color", sa.String(length=7), nullable=False),
        sa.Column("position", sa.SmallInteger(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint("accrual IN ('yearly', 'monthly')", name=op.f("ck_leave_types_accrual")),
        sa.CheckConstraint("color ~ '^#[0-9a-fA-F]{6}$'", name=op.f("ck_leave_types_color")),
        sa.CheckConstraint("carry_over_max >= 0", name=op.f("ck_leave_types_carry")),
        sa.CheckConstraint("days_per_year IS NULL OR days_per_year >= 0", name=op.f("ck_leave_types_days")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_leave_types")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_leave_types_tenant_id_id")),
    )
    op.create_index(op.f("ix_leave_types_tenant_id"), "leave_types", ["tenant_id"], unique=False)
    op.create_index(
        "uq_leave_types_name", "leave_types", ["tenant_id", sa.literal_column("lower(name)")], unique=True
    )
    op.create_table(
        "holidays",
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("branch_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "branch_id"],
            ["branches.tenant_id", "branches.id"],
            name=op.f("fk_holidays_tenant_id_branch_id_branches"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_holidays")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_holidays_tenant_id_id")),
    )
    op.create_index(op.f("ix_holidays_tenant_id"), "holidays", ["tenant_id"], unique=False)
    op.create_index(
        "uq_holidays_day",
        "holidays",
        [
            "tenant_id",
            "day",
            sa.literal_column("coalesce(branch_id, '00000000-0000-0000-0000-000000000000'::uuid)"),
        ],
        unique=True,
    )
    op.create_table(
        "leave_adjustments",
        sa.Column("employee_id", sa.Uuid(), nullable=False),
        sa.Column("leave_type_id", sa.Uuid(), nullable=False),
        sa.Column("year", sa.SmallInteger(), nullable=False),
        sa.Column("days", sa.Numeric(precision=6, scale=1), nullable=False),
        sa.Column("reason", sa.String(length=300), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("days <> 0", name=op.f("ck_leave_adjustments_days")),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_leave_adjustments_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "employee_id"],
            ["employees.tenant_id", "employees.id"],
            name=op.f("fk_leave_adjustments_tenant_id_employee_id_employees"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "leave_type_id"],
            ["leave_types.tenant_id", "leave_types.id"],
            name=op.f("fk_leave_adjustments_tenant_id_leave_type_id_leave_types"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_leave_adjustments")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_leave_adjustments_tenant_id_id")),
    )
    op.create_index(
        "ix_leave_adjustments_lookup",
        "leave_adjustments",
        ["tenant_id", "employee_id", "leave_type_id", "year"],
        unique=False,
    )
    op.create_index(op.f("ix_leave_adjustments_tenant_id"), "leave_adjustments", ["tenant_id"], unique=False)
    op.create_table(
        "leave_requests",
        sa.Column("employee_id", sa.Uuid(), nullable=False),
        sa.Column("leave_type_id", sa.Uuid(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("half_day", sa.String(length=10), nullable=False),
        sa.Column("days", sa.Numeric(precision=6, scale=1), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("requested_by", sa.Uuid(), nullable=True),
        sa.Column("decided_by", sa.Uuid(), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decision_note", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        postgresql.ExcludeConstraint(
            (sa.column("tenant_id"), "="),
            (sa.column("employee_id"), "="),
            (sa.text("daterange(start_date, end_date, '[]')"), "&&"),
            where=sa.text("status IN ('pending', 'approved')"),
            using="gist",
            name="leave_no_overlap",
        ),
        sa.CheckConstraint(
            "half_day = 'none' OR start_date = end_date", name=op.f("ck_leave_requests_half_single_day")
        ),
        sa.CheckConstraint(
            "half_day IN ('none', 'morning', 'afternoon')", name=op.f("ck_leave_requests_half_day")
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'approved', 'rejected', 'cancelled')",
            name=op.f("ck_leave_requests_status"),
        ),
        sa.CheckConstraint("days > 0", name=op.f("ck_leave_requests_days")),
        sa.CheckConstraint("end_date >= start_date", name=op.f("ck_leave_requests_order")),
        sa.ForeignKeyConstraint(
            ["decided_by"], ["users.id"], name=op.f("fk_leave_requests_decided_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["requested_by"], ["users.id"], name=op.f("fk_leave_requests_requested_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "employee_id"],
            ["employees.tenant_id", "employees.id"],
            name=op.f("fk_leave_requests_tenant_id_employee_id_employees"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "leave_type_id"],
            ["leave_types.tenant_id", "leave_types.id"],
            name=op.f("fk_leave_requests_tenant_id_leave_type_id_leave_types"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_leave_requests")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_leave_requests_tenant_id_id")),
    )
    op.create_index(
        "ix_leave_requests_employee",
        "leave_requests",
        ["tenant_id", "employee_id", "start_date"],
        unique=False,
    )
    op.create_index("ix_leave_requests_status", "leave_requests", ["tenant_id", "status"], unique=False)
    op.create_index(op.f("ix_leave_requests_tenant_id"), "leave_requests", ["tenant_id"], unique=False)
    # ### end Alembic commands ###
    for table in ("leave_policies", "leave_types", "holidays", "leave_adjustments", "leave_requests"):
        rls.tenant_table(table)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_leave_requests_tenant_id"), table_name="leave_requests")
    op.drop_index("ix_leave_requests_status", table_name="leave_requests")
    op.drop_index("ix_leave_requests_employee", table_name="leave_requests")
    op.drop_table("leave_requests")
    op.drop_index(op.f("ix_leave_adjustments_tenant_id"), table_name="leave_adjustments")
    op.drop_index("ix_leave_adjustments_lookup", table_name="leave_adjustments")
    op.drop_table("leave_adjustments")
    op.drop_index("uq_holidays_day", table_name="holidays")
    op.drop_index(op.f("ix_holidays_tenant_id"), table_name="holidays")
    op.drop_table("holidays")
    op.drop_index("uq_leave_types_name", table_name="leave_types")
    op.drop_index(op.f("ix_leave_types_tenant_id"), table_name="leave_types")
    op.drop_table("leave_types")
    op.drop_table("leave_policies")
    # ### end Alembic commands ###
