"""books: inventory (stock ledger, suppliers, purchases, transfers, counts) and accounting

Revision ID: 0021
Revises: 0020
Create Date: 2026-10-04 23:14:53.536764
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from migrations import rls

revision: str = "0021"
down_revision: str | None = "0020"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accounting_settings",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("locked_until", sa.Date(), nullable=True),
        sa.Column("tax_accounts", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("expense_accounts", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("next_number", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("tenant_id", name=op.f("pk_accounting_settings")),
    )
    op.create_table(
        "accounts",
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("type", sa.String(length=10), nullable=False),
        sa.Column("role", sa.String(length=30), nullable=True),
        sa.Column("active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "type IN ('asset', 'liability', 'equity', 'income', 'expense')", name=op.f("ck_accounts_type")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_accounts")),
        sa.UniqueConstraint("tenant_id", "code", name=op.f("uq_accounts_tenant_id_code")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_accounts_tenant_id_id")),
    )
    op.create_index(op.f("ix_accounts_tenant_id"), "accounts", ["tenant_id"], unique=False)
    op.create_index(
        "uq_accounts_role",
        "accounts",
        ["tenant_id", "role"],
        unique=True,
        postgresql_where=sa.text("role IS NOT NULL"),
    )
    op.create_table(
        "suppliers",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("phone", sa.String(length=40), nullable=True),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("tax_id", sa.String(length=60), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_suppliers")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_suppliers_tenant_id_id")),
    )
    op.create_index(op.f("ix_suppliers_tenant_id"), "suppliers", ["tenant_id"], unique=False)
    op.create_table(
        "tax_return_templates",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("boxes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tax_return_templates")),
    )
    op.create_index(
        op.f("ix_tax_return_templates_tenant_id"), "tax_return_templates", ["tenant_id"], unique=False
    )
    op.create_table(
        "journal_entries",
        sa.Column("number", sa.BigInteger(), nullable=False),
        sa.Column("entry_date", sa.Date(), nullable=False),
        sa.Column("memo", sa.String(length=300), nullable=False),
        sa.Column("source_type", sa.String(length=30), nullable=True),
        sa.Column("source_id", sa.Uuid(), nullable=True),
        sa.Column("reason", sa.String(length=60), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("reversed_by", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_journal_entries_created_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_journal_entries")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_journal_entries_tenant_id_id")),
        sa.UniqueConstraint("tenant_id", "number", name=op.f("uq_journal_entries_tenant_id_number")),
    )
    op.create_index("ix_journal_date", "journal_entries", ["tenant_id", "entry_date"], unique=False)
    op.create_index(op.f("ix_journal_entries_tenant_id"), "journal_entries", ["tenant_id"], unique=False)
    op.create_index(
        "uq_journal_source",
        "journal_entries",
        ["tenant_id", "source_type", "source_id", "reason"],
        unique=True,
        postgresql_where=sa.text("source_id IS NOT NULL"),
    )
    op.create_table(
        "purchases",
        sa.Column("supplier_id", sa.Uuid(), nullable=True),
        sa.Column("branch_id", sa.Uuid(), nullable=True),
        sa.Column("reference", sa.String(length=60), nullable=True),
        sa.Column("received_on", sa.Date(), nullable=False),
        sa.Column("net", sa.BigInteger(), nullable=False),
        sa.Column("tax", sa.BigInteger(), nullable=False),
        sa.Column("total", sa.BigInteger(), nullable=False),
        sa.Column("paid", sa.BigInteger(), nullable=False),
        sa.Column("paid_from", sa.String(length=12), nullable=False),
        sa.Column("lines", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], name=op.f("fk_purchases_created_by_users")),
        sa.ForeignKeyConstraint(
            ["tenant_id", "supplier_id"],
            ["suppliers.tenant_id", "suppliers.id"],
            name=op.f("fk_purchases_tenant_id_supplier_id_suppliers"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_purchases")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_purchases_tenant_id_id")),
    )
    op.create_index("ix_purchases_day", "purchases", ["tenant_id", "received_on"], unique=False)
    op.create_index(op.f("ix_purchases_tenant_id"), "purchases", ["tenant_id"], unique=False)
    op.create_table(
        "stock_counts",
        sa.Column("branch_id", sa.Uuid(), nullable=True),
        sa.Column("counted_on", sa.Date(), nullable=False),
        sa.Column("lines", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("items", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], name=op.f("fk_stock_counts_created_by_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_counts")),
    )
    op.create_index(op.f("ix_stock_counts_tenant_id"), "stock_counts", ["tenant_id"], unique=False)
    op.create_table(
        "stock_items",
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("track", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("reorder_level", sa.Numeric(precision=14, scale=3), nullable=True),
        sa.Column("quantity", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("value", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("average_cost", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "product_id"],
            ["products.tenant_id", "products.id"],
            name=op.f("fk_stock_items_tenant_id_product_id_products"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("product_id", name=op.f("pk_stock_items")),
    )
    op.create_index(op.f("ix_stock_items_tenant_id"), "stock_items", ["tenant_id"], unique=False)
    op.create_table(
        "stock_levels",
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("branch_id", sa.Uuid(), nullable=True),
        sa.Column("branch_key", sa.Uuid(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("low_since", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "product_id"],
            ["products.tenant_id", "products.id"],
            name=op.f("fk_stock_levels_tenant_id_product_id_products"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_levels")),
        sa.UniqueConstraint(
            "tenant_id",
            "product_id",
            "branch_key",
            name=op.f("uq_stock_levels_tenant_id_product_id_branch_key"),
        ),
    )
    op.create_index(op.f("ix_stock_levels_tenant_id"), "stock_levels", ["tenant_id"], unique=False)
    op.create_table(
        "stock_movements",
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("branch_id", sa.Uuid(), nullable=True),
        sa.Column("kind", sa.String(length=14), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("unit_cost", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("value", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ref_type", sa.String(length=20), nullable=True),
        sa.Column("ref_id", sa.Uuid(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "kind IN ('opening', 'purchase', 'sale', 'return', 'void', 'adjustment', 'count', 'transfer_out', 'transfer_in')",
            name=op.f("ck_stock_movements_kind"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_stock_movements_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "product_id"],
            ["products.tenant_id", "products.id"],
            name=op.f("fk_stock_movements_tenant_id_product_id_products"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_movements")),
    )
    op.create_index(
        "ix_stock_movements_product",
        "stock_movements",
        ["tenant_id", "product_id", "occurred_at"],
        unique=False,
    )
    op.create_index(
        "ix_stock_movements_ref", "stock_movements", ["tenant_id", "ref_type", "ref_id"], unique=False
    )
    op.create_index(op.f("ix_stock_movements_tenant_id"), "stock_movements", ["tenant_id"], unique=False)
    op.create_table(
        "stock_transfers",
        sa.Column("from_branch_id", sa.Uuid(), nullable=True),
        sa.Column("to_branch_id", sa.Uuid(), nullable=True),
        sa.Column("lines", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_stock_transfers_created_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_transfers")),
    )
    op.create_index(op.f("ix_stock_transfers_tenant_id"), "stock_transfers", ["tenant_id"], unique=False)
    op.create_table(
        "supplier_entries",
        sa.Column("supplier_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=12), nullable=False),
        sa.Column("amount", sa.BigInteger(), nullable=False),
        sa.Column("occurred_on", sa.Date(), nullable=False),
        sa.Column("purchase_id", sa.Uuid(), nullable=True),
        sa.Column("paid_from", sa.String(length=12), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "kind IN ('purchase', 'payment', 'adjustment')", name=op.f("ck_supplier_entries_kind")
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_supplier_entries_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "supplier_id"],
            ["suppliers.tenant_id", "suppliers.id"],
            name=op.f("fk_supplier_entries_tenant_id_supplier_id_suppliers"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_supplier_entries")),
    )
    op.create_index(
        "ix_supplier_entries_supplier",
        "supplier_entries",
        ["tenant_id", "supplier_id", "occurred_on"],
        unique=False,
    )
    op.create_index(op.f("ix_supplier_entries_tenant_id"), "supplier_entries", ["tenant_id"], unique=False)
    op.create_table(
        "journal_lines",
        sa.Column("entry_id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("debit", sa.BigInteger(), nullable=False),
        sa.Column("credit", sa.BigInteger(), nullable=False),
        sa.Column("description", sa.String(length=300), nullable=True),
        sa.Column("tax_rate_id", sa.Uuid(), nullable=True),
        sa.Column("tax_base", sa.BigInteger(), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "debit >= 0 AND credit >= 0 AND (debit = 0 OR credit = 0)", name=op.f("ck_journal_lines_one_side")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "account_id"],
            ["accounts.tenant_id", "accounts.id"],
            name=op.f("fk_journal_lines_tenant_id_account_id_accounts"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "entry_id"],
            ["journal_entries.tenant_id", "journal_entries.id"],
            name=op.f("fk_journal_lines_tenant_id_entry_id_journal_entries"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_journal_lines")),
    )
    op.create_index("ix_journal_lines_account", "journal_lines", ["tenant_id", "account_id"], unique=False)
    op.create_index("ix_journal_lines_entry", "journal_lines", ["tenant_id", "entry_id"], unique=False)
    op.create_index(op.f("ix_journal_lines_tenant_id"), "journal_lines", ["tenant_id"], unique=False)
    rls.tenant_table("accounting_settings")
    rls.tenant_table("accounts")
    rls.tenant_table("suppliers")
    rls.tenant_table("tax_return_templates")
    rls.tenant_table("journal_entries")
    rls.tenant_table("purchases")
    rls.tenant_table("stock_counts")
    rls.tenant_table("stock_items")
    rls.tenant_table("stock_levels")
    rls.tenant_table("stock_movements")
    rls.tenant_table("stock_transfers")
    rls.tenant_table("supplier_entries")
    rls.tenant_table("journal_lines")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_journal_lines_tenant_id"), table_name="journal_lines")
    op.drop_index("ix_journal_lines_entry", table_name="journal_lines")
    op.drop_index("ix_journal_lines_account", table_name="journal_lines")
    op.drop_table("journal_lines")
    op.drop_index(op.f("ix_supplier_entries_tenant_id"), table_name="supplier_entries")
    op.drop_index("ix_supplier_entries_supplier", table_name="supplier_entries")
    op.drop_table("supplier_entries")
    op.drop_index(op.f("ix_stock_transfers_tenant_id"), table_name="stock_transfers")
    op.drop_table("stock_transfers")
    op.drop_index(op.f("ix_stock_movements_tenant_id"), table_name="stock_movements")
    op.drop_index("ix_stock_movements_ref", table_name="stock_movements")
    op.drop_index("ix_stock_movements_product", table_name="stock_movements")
    op.drop_table("stock_movements")
    op.drop_index(op.f("ix_stock_levels_tenant_id"), table_name="stock_levels")
    op.drop_table("stock_levels")
    op.drop_index(op.f("ix_stock_items_tenant_id"), table_name="stock_items")
    op.drop_table("stock_items")
    op.drop_index(op.f("ix_stock_counts_tenant_id"), table_name="stock_counts")
    op.drop_table("stock_counts")
    op.drop_index(op.f("ix_purchases_tenant_id"), table_name="purchases")
    op.drop_index("ix_purchases_day", table_name="purchases")
    op.drop_table("purchases")
    op.drop_index(
        "uq_journal_source", table_name="journal_entries", postgresql_where=sa.text("source_id IS NOT NULL")
    )
    op.drop_index(op.f("ix_journal_entries_tenant_id"), table_name="journal_entries")
    op.drop_index("ix_journal_date", table_name="journal_entries")
    op.drop_table("journal_entries")
    op.drop_index(op.f("ix_tax_return_templates_tenant_id"), table_name="tax_return_templates")
    op.drop_table("tax_return_templates")
    op.drop_index(op.f("ix_suppliers_tenant_id"), table_name="suppliers")
    op.drop_table("suppliers")
    op.drop_index("uq_accounts_role", table_name="accounts", postgresql_where=sa.text("role IS NOT NULL"))
    op.drop_index(op.f("ix_accounts_tenant_id"), table_name="accounts")
    op.drop_table("accounts")
    op.drop_table("accounting_settings")
    # ### end Alembic commands ###
