"""signals: dismissals, and whether signals may be about individual people

Revision ID: 0019
Revises: 0018
Create Date: 2026-10-04 22:49:24.968377
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from migrations import rls

revision: str = "0019"
down_revision: str | None = "0018"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "signal_dismissals",
        sa.Column("membership_id", sa.Uuid(), nullable=False),
        sa.Column("key", sa.String(length=200), nullable=False),
        sa.Column("until", sa.Date(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "membership_id"],
            ["memberships.tenant_id", "memberships.id"],
            name=op.f("fk_signal_dismissals_tenant_id_membership_id_memberships"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_signal_dismissals")),
        sa.UniqueConstraint(
            "tenant_id", "membership_id", "key", name=op.f("uq_signal_dismissals_tenant_id_membership_id_key")
        ),
    )
    op.create_index(op.f("ix_signal_dismissals_tenant_id"), "signal_dismissals", ["tenant_id"], unique=False)
    op.add_column(
        "ai_settings",
        sa.Column("signal_people", sa.Boolean(), server_default=sa.text("false"), nullable=False),
    )
    rls.tenant_table("signal_dismissals")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ai_settings", "signal_people")
    op.drop_index(op.f("ix_signal_dismissals_tenant_id"), table_name="signal_dismissals")
    op.drop_table("signal_dismissals")
    # ### end Alembic commands ###
