"""ai: workspace AI settings, usage, conversations, and allowances per plan

Revision ID: 0015
Revises: 0014
Create Date: 2026-10-04 21:41:08.608536
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from migrations import rls

revision: str = "0015"
down_revision: str | None = "0014"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_allowances",
        sa.Column("plan_key", sa.String(length=40), nullable=False),
        sa.Column("questions_per_month", sa.Integer(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(["plan_key"], ["plans.key"], name=op.f("fk_ai_allowances_plan_key_plans")),
        sa.ForeignKeyConstraint(["updated_by"], ["users.id"], name=op.f("fk_ai_allowances_updated_by_users")),
        sa.PrimaryKeyConstraint("plan_key", name=op.f("pk_ai_allowances")),
    )
    op.create_table(
        "ai_settings",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("terms_accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("terms_accepted_by", sa.Uuid(), nullable=True),
        sa.Column("features", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["terms_accepted_by"], ["users.id"], name=op.f("fk_ai_settings_terms_accepted_by_users")
        ),
        sa.PrimaryKeyConstraint("tenant_id", name=op.f("pk_ai_settings")),
    )
    op.create_table(
        "ai_conversations",
        sa.Column("membership_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "membership_id"],
            ["memberships.tenant_id", "memberships.id"],
            name=op.f("fk_ai_conversations_tenant_id_membership_id_memberships"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_conversations")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_ai_conversations_tenant_id_id")),
    )
    op.create_index(
        "ix_ai_conversations_member", "ai_conversations", ["tenant_id", "membership_id"], unique=False
    )
    op.create_index(op.f("ix_ai_conversations_tenant_id"), "ai_conversations", ["tenant_id"], unique=False)
    op.create_table(
        "ai_usage",
        sa.Column("membership_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("model", sa.String(length=80), nullable=False),
        sa.Column("tokens_in", sa.Integer(), nullable=False),
        sa.Column("tokens_out", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "membership_id"],
            ["memberships.tenant_id", "memberships.id"],
            name=op.f("fk_ai_usage_tenant_id_membership_id_memberships"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_usage")),
    )
    op.create_index("ix_ai_usage_month", "ai_usage", ["tenant_id", "created_at"], unique=False)
    op.create_index(op.f("ix_ai_usage_tenant_id"), "ai_usage", ["tenant_id"], unique=False)
    op.create_table(
        "ai_messages",
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.String(length=10), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("sources", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("role IN ('user', 'assistant')", name=op.f("ck_ai_messages_role")),
        sa.ForeignKeyConstraint(
            ["tenant_id", "conversation_id"],
            ["ai_conversations.tenant_id", "ai_conversations.id"],
            name=op.f("fk_ai_messages_tenant_id_conversation_id_ai_conversations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_messages")),
    )
    op.create_index(
        "ix_ai_messages_conversation", "ai_messages", ["tenant_id", "conversation_id"], unique=False
    )
    op.create_index(op.f("ix_ai_messages_tenant_id"), "ai_messages", ["tenant_id"], unique=False)
    # ### end Alembic commands ###
    for table in ("ai_settings", "ai_usage", "ai_conversations", "ai_messages"):
        rls.tenant_table(table)
    # Operators change allowances through the app, so the app role may update them.
    rls.global_table("ai_allowances", privileges="SELECT, INSERT, UPDATE")
    # Starting allowances (questions a month); operators change them without a release.
    allowances = sa.table(
        "ai_allowances", sa.column("plan_key", sa.String), sa.column("questions_per_month", sa.Integer)
    )
    op.bulk_insert(
        allowances,
        [
            {"plan_key": "free", "questions_per_month": 0},
            {"plan_key": "starter", "questions_per_month": 100},
            {"plan_key": "growth", "questions_per_month": 500},
            {"plan_key": "business", "questions_per_month": 2000},
            {"plan_key": "enterprise", "questions_per_month": None},
        ],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ai_messages_tenant_id"), table_name="ai_messages")
    op.drop_index("ix_ai_messages_conversation", table_name="ai_messages")
    op.drop_table("ai_messages")
    op.drop_index(op.f("ix_ai_usage_tenant_id"), table_name="ai_usage")
    op.drop_index("ix_ai_usage_month", table_name="ai_usage")
    op.drop_table("ai_usage")
    op.drop_index(op.f("ix_ai_conversations_tenant_id"), table_name="ai_conversations")
    op.drop_index("ix_ai_conversations_member", table_name="ai_conversations")
    op.drop_table("ai_conversations")
    op.drop_table("ai_settings")
    op.drop_table("ai_allowances")
    # ### end Alembic commands ###
