"""report subscriptions: overview reports emailed every week or month

Revision ID: 0014
Revises: 0013
Create Date: 2026-10-01 13:41:30.281296
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from migrations import rls

revision: str = "0014"
down_revision: str | None = "0013"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "report_subscriptions",
        sa.Column("membership_id", sa.Uuid(), nullable=False),
        sa.Column("frequency", sa.String(length=10), nullable=False),
        sa.Column("department_id", sa.Uuid(), nullable=True),
        sa.Column("last_sent_on", sa.Date(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "frequency IN ('weekly', 'monthly')", name=op.f("ck_report_subscriptions_frequency")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "department_id"],
            ["departments.tenant_id", "departments.id"],
            name=op.f("fk_report_subscriptions_tenant_id_department_id_departments"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "membership_id"],
            ["memberships.tenant_id", "memberships.id"],
            name=op.f("fk_report_subscriptions_tenant_id_membership_id_memberships"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_report_subscriptions")),
        sa.UniqueConstraint(
            "tenant_id",
            "membership_id",
            "frequency",
            name=op.f("uq_report_subscriptions_tenant_id_membership_id_frequency"),
        ),
    )
    op.create_index(
        op.f("ix_report_subscriptions_tenant_id"), "report_subscriptions", ["tenant_id"], unique=False
    )
    # ### end Alembic commands ###
    rls.tenant_table("report_subscriptions")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_report_subscriptions_tenant_id"), table_name="report_subscriptions")
    op.drop_table("report_subscriptions")
    # ### end Alembic commands ###
