"""automations and their runs

Revision ID: 0018
Revises: 0017
Create Date: 2026-10-04 22:41:20.650450
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from migrations import rls

revision: str = "0018"
down_revision: str | None = "0017"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "automations",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("trigger", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("conditions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("actions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("owner_membership_id", sa.Uuid(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("drafted_by_ai", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("next_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("paused_reason", sa.String(length=200), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_automations_created_by_users"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "owner_membership_id"],
            ["memberships.tenant_id", "memberships.id"],
            name=op.f("fk_automations_tenant_id_owner_membership_id_memberships"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_automations")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_automations_tenant_id_id")),
    )
    op.create_index(
        "ix_automations_due", "automations", ["tenant_id", "enabled", "next_run_at"], unique=False
    )
    op.create_index(op.f("ix_automations_tenant_id"), "automations", ["tenant_id"], unique=False)
    op.create_table(
        "automation_runs",
        sa.Column("automation_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("cause", sa.String(length=80), nullable=False),
        sa.Column("event_id", sa.Uuid(), nullable=True),
        sa.Column("detail", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "status IN ('ok', 'skipped', 'failed', 'limited')", name=op.f("ck_automation_runs_status")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "automation_id"],
            ["automations.tenant_id", "automations.id"],
            name=op.f("fk_automation_runs_tenant_id_automation_id_automations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_automation_runs")),
    )
    op.create_index(
        "ix_automation_runs_recent",
        "automation_runs",
        ["tenant_id", "automation_id", "created_at"],
        unique=False,
    )
    op.create_index(op.f("ix_automation_runs_tenant_id"), "automation_runs", ["tenant_id"], unique=False)
    rls.tenant_table("automations")
    rls.tenant_table("automation_runs")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_automation_runs_tenant_id"), table_name="automation_runs")
    op.drop_index("ix_automation_runs_recent", table_name="automation_runs")
    op.drop_table("automation_runs")
    op.drop_index(op.f("ix_automations_tenant_id"), table_name="automations")
    op.drop_index("ix_automations_due", table_name="automations")
    op.drop_table("automations")
    # ### end Alembic commands ###
