"""tills

Revision ID: 0026
Revises: 0025
Create Date: 2026-10-05 04:11:08.313644
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from migrations import rls

revision: str = "0026"
down_revision: str | None = "0025"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cashier_pins",
        sa.Column("membership_id", sa.Uuid(), nullable=False),
        sa.Column("pin_hash", sa.String(length=200), nullable=False),
        sa.Column("failures", sa.Integer(), nullable=False),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("membership_id", name=op.f("pk_cashier_pins")),
    )
    op.create_index(op.f("ix_cashier_pins_tenant_id"), "cashier_pins", ["tenant_id"], unique=False)
    op.create_table(
        "tills",
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("branch_id", sa.Uuid(), nullable=True),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("hint", sa.String(length=8), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], name=op.f("fk_tills_created_by_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tills")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_tills_tenant_id_id")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_tills_token_hash")),
    )
    op.create_index(op.f("ix_tills_tenant_id"), "tills", ["tenant_id"], unique=False)
    op.add_column("auth_sessions", sa.Column("device_id", sa.Uuid(), nullable=True))
    rls.tenant_table("tills")
    rls.tenant_table("cashier_pins")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("auth_sessions", "device_id")
    op.drop_index(op.f("ix_tills_tenant_id"), table_name="tills")
    op.drop_table("tills")
    op.drop_index(op.f("ix_cashier_pins_tenant_id"), table_name="cashier_pins")
    op.drop_table("cashier_pins")
    # ### end Alembic commands ###
