"""notifications: each person's in-app inbox, filled from domain events

Revision ID: 0007
Revises: 0006
Create Date: 2026-10-01 06:17:54.046416
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from migrations import rls

revision: str = "0007"
down_revision: str | None = "0006"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notifications",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=80), nullable=False),
        sa.Column("event_id", sa.Uuid(), nullable=True),
        sa.Column("actor_name", sa.String(length=120), nullable=True),
        sa.Column("subject_type", sa.String(length=40), nullable=True),
        sa.Column("subject_id", sa.String(length=64), nullable=True),
        sa.Column("link", sa.String(length=200), nullable=True),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("emailed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_notifications_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
    )
    op.create_index(
        "ix_notifications_inbox", "notifications", ["tenant_id", "user_id", "created_at"], unique=False
    )
    op.create_index(op.f("ix_notifications_tenant_id"), "notifications", ["tenant_id"], unique=False)
    op.create_index(
        "ix_notifications_unread",
        "notifications",
        ["tenant_id", "user_id"],
        unique=False,
        postgresql_where=sa.text("read_at IS NULL"),
    )
    # ### end Alembic commands ###
    # People mark them read (UPDATE); old ones are deleted by the maintenance job as owner.
    rls.tenant_table("notifications", privileges="SELECT, INSERT, UPDATE")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_notifications_unread", table_name="notifications", postgresql_where=sa.text("read_at IS NULL")
    )
    op.drop_index(op.f("ix_notifications_tenant_id"), table_name="notifications")
    op.drop_index("ix_notifications_inbox", table_name="notifications")
    op.drop_table("notifications")
    # ### end Alembic commands ###
