"""scim, sandbox

Revision ID: 0025
Revises: 0024
Create Date: 2026-10-05 03:57:49.312788
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0025"
down_revision: str | None = "0024"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("memberships", sa.Column("external_id", sa.String(length=200), nullable=True))
    op.add_column("tenants", sa.Column("sandbox_of", sa.Uuid(), nullable=True))
    op.create_foreign_key(
        op.f("fk_tenants_sandbox_of_tenants"),
        "tenants",
        "tenants",
        ["sandbox_of"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_tenants_sandbox_of_tenants"), "tenants", type_="foreignkey")
    op.drop_column("tenants", "sandbox_of")
    op.drop_column("memberships", "external_id")
    # ### end Alembic commands ###
