"""onboarding: join links, workspace address history, sample data, checklist

Revision ID: 0022
Revises: 0021
Create Date: 2026-10-04 23:25:17.701508
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from migrations import rls

revision: str = "0022"
down_revision: str | None = "0021"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sample_records",
        sa.Column("table_name", sa.String(length=60), nullable=False),
        sa.Column("record_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sample_records")),
    )
    op.create_index(op.f("ix_sample_records_tenant_id"), "sample_records", ["tenant_id"], unique=False)
    op.create_table(
        "join_links",
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("hint", sa.String(length=8), nullable=False),
        sa.Column("label", sa.String(length=120), nullable=True),
        sa.Column("role_id", sa.Uuid(), nullable=False),
        sa.Column("scope_department_id", sa.Uuid(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("max_uses", sa.Integer(), nullable=False),
        sa.Column("uses", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], name=op.f("fk_join_links_created_by_users")),
        sa.ForeignKeyConstraint(
            ["tenant_id", "role_id"],
            ["roles.tenant_id", "roles.id"],
            name=op.f("fk_join_links_tenant_id_role_id_roles"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_join_links")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_join_links_tenant_id_id")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_join_links_token_hash")),
    )
    op.create_index(op.f("ix_join_links_tenant_id"), "join_links", ["tenant_id"], unique=False)
    op.add_column(
        "tenants",
        sa.Column(
            "previous_slugs", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False
        ),
    )
    op.add_column("tenants", sa.Column("checklist_dismissed_at", sa.DateTime(timezone=True), nullable=True))
    rls.tenant_table("sample_records")
    rls.tenant_table("join_links")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tenants", "checklist_dismissed_at")
    op.drop_column("tenants", "previous_slugs")
    op.drop_index(op.f("ix_join_links_tenant_id"), table_name="join_links")
    op.drop_table("join_links")
    op.drop_index(op.f("ix_sample_records_tenant_id"), table_name="sample_records")
    op.drop_table("sample_records")
    # ### end Alembic commands ###
