"""payroll: settings, salaries, advances, runs, payslips and one-off items

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-01 01:11:20.352133
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from migrations import rls

revision: str = "0004"
down_revision: str | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "payroll_settings",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("day_basis", sa.String(length=10), nullable=False),
        sa.Column("hours_per_day", sa.SmallInteger(), nullable=False),
        sa.Column("overtime_multiplier", sa.Numeric(precision=4, scale=2), nullable=False),
        sa.Column("overtime_divisor", sa.SmallInteger(), nullable=False),
        sa.Column("bonus_percent", sa.SmallInteger(), nullable=False),
        sa.Column("bonus_min_months", sa.SmallInteger(), nullable=False),
        sa.Column("round_net", sa.Boolean(), nullable=False),
        sa.Column("tax_enabled", sa.Boolean(), nullable=False),
        sa.Column("tax_table", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint("day_basis IN ('calendar', 'thirty')", name=op.f("ck_payroll_settings_day_basis")),
        sa.CheckConstraint(
            "bonus_min_months BETWEEN 0 AND 60", name=op.f("ck_payroll_settings_bonus_months")
        ),
        sa.CheckConstraint("bonus_percent BETWEEN 0 AND 500", name=op.f("ck_payroll_settings_bonus_percent")),
        sa.CheckConstraint("hours_per_day BETWEEN 1 AND 16", name=op.f("ck_payroll_settings_hours")),
        sa.CheckConstraint("overtime_divisor BETWEEN 1 AND 400", name=op.f("ck_payroll_settings_ot_divisor")),
        sa.CheckConstraint(
            "overtime_multiplier BETWEEN 1 AND 5", name=op.f("ck_payroll_settings_ot_multiplier")
        ),
        sa.PrimaryKeyConstraint("tenant_id", name=op.f("pk_payroll_settings")),
    )
    op.create_table(
        "payroll_runs",
        sa.Column("period", sa.String(length=7), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("bonus_label", sa.String(length=80), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("headcount", sa.Integer(), nullable=False),
        sa.Column("gross", sa.BigInteger(), nullable=False),
        sa.Column("deductions", sa.BigInteger(), nullable=False),
        sa.Column("net", sa.BigInteger(), nullable=False),
        sa.Column("computed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("submitted_by", sa.Uuid(), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finalized_by", sa.Uuid(), nullable=True),
        sa.Column("finalized_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint("period ~ '^[0-9]{4}-(0[1-9]|1[0-2])$'", name=op.f("ck_payroll_runs_period")),
        sa.CheckConstraint(
            "status IN ('draft', 'review', 'finalized', 'paid')", name=op.f("ck_payroll_runs_status")
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], name=op.f("fk_payroll_runs_created_by_users")),
        sa.ForeignKeyConstraint(
            ["finalized_by"], ["users.id"], name=op.f("fk_payroll_runs_finalized_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["submitted_by"], ["users.id"], name=op.f("fk_payroll_runs_submitted_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payroll_runs")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_payroll_runs_tenant_id_id")),
        sa.UniqueConstraint("tenant_id", "period", name=op.f("uq_payroll_runs_tenant_id_period")),
    )
    op.create_index(op.f("ix_payroll_runs_tenant_id"), "payroll_runs", ["tenant_id"], unique=False)
    op.create_table(
        "payroll_items",
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("employee_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=10), nullable=False),
        sa.Column("label", sa.String(length=120), nullable=False),
        sa.Column("amount", sa.BigInteger(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("kind IN ('earning', 'deduction')", name=op.f("ck_payroll_items_kind")),
        sa.CheckConstraint("amount > 0", name=op.f("ck_payroll_items_amount")),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], name=op.f("fk_payroll_items_created_by_users")),
        sa.ForeignKeyConstraint(
            ["tenant_id", "employee_id"],
            ["employees.tenant_id", "employees.id"],
            name=op.f("fk_payroll_items_tenant_id_employee_id_employees"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "run_id"],
            ["payroll_runs.tenant_id", "payroll_runs.id"],
            name=op.f("fk_payroll_items_tenant_id_run_id_payroll_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payroll_items")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_payroll_items_tenant_id_id")),
    )
    op.create_index("ix_payroll_items_run", "payroll_items", ["tenant_id", "run_id"], unique=False)
    op.create_index(op.f("ix_payroll_items_tenant_id"), "payroll_items", ["tenant_id"], unique=False)
    op.create_table(
        "payroll_loans",
        sa.Column("employee_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=8), nullable=False),
        sa.Column("label", sa.String(length=120), nullable=False),
        sa.Column("principal", sa.BigInteger(), nullable=False),
        sa.Column("installment", sa.BigInteger(), nullable=False),
        sa.Column("outstanding", sa.BigInteger(), nullable=False),
        sa.Column("start_period", sa.String(length=7), nullable=False),
        sa.Column("status", sa.String(length=8), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint("kind IN ('advance', 'loan')", name=op.f("ck_payroll_loans_kind")),
        sa.CheckConstraint("status IN ('active', 'closed')", name=op.f("ck_payroll_loans_status")),
        sa.CheckConstraint(
            "outstanding >= 0 AND outstanding <= principal", name=op.f("ck_payroll_loans_outstanding")
        ),
        sa.CheckConstraint("principal > 0 AND installment > 0", name=op.f("ck_payroll_loans_positive")),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], name=op.f("fk_payroll_loans_created_by_users")),
        sa.ForeignKeyConstraint(
            ["tenant_id", "employee_id"],
            ["employees.tenant_id", "employees.id"],
            name=op.f("fk_payroll_loans_tenant_id_employee_id_employees"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payroll_loans")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_payroll_loans_tenant_id_id")),
    )
    op.create_index(
        "ix_payroll_loans_employee", "payroll_loans", ["tenant_id", "employee_id", "status"], unique=False
    )
    op.create_index(op.f("ix_payroll_loans_tenant_id"), "payroll_loans", ["tenant_id"], unique=False)
    op.create_table(
        "payslips",
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("employee_id", sa.Uuid(), nullable=False),
        sa.Column("employee_name", sa.String(length=200), nullable=False),
        sa.Column("employee_code", sa.String(length=40), nullable=True),
        sa.Column("department_id", sa.Uuid(), nullable=True),
        sa.Column("department_name", sa.String(length=120), nullable=True),
        sa.Column("job_title", sa.String(length=120), nullable=True),
        sa.Column("pay_rule", sa.String(length=10), nullable=False),
        sa.Column("structure_id", sa.Uuid(), nullable=True),
        sa.Column("days_in_period", sa.SmallInteger(), nullable=False),
        sa.Column("payable_days", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("unpaid_leave_days", sa.Numeric(precision=6, scale=1), nullable=False),
        sa.Column("worked_minutes", sa.Integer(), nullable=False),
        sa.Column("overtime_minutes", sa.Integer(), nullable=False),
        sa.Column("lines", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("gross", sa.BigInteger(), nullable=False),
        sa.Column("deductions", sa.BigInteger(), nullable=False),
        sa.Column("net", sa.BigInteger(), nullable=False),
        sa.Column("carried_forward", sa.BigInteger(), nullable=False),
        sa.Column("payment_method", sa.String(length=8), nullable=False),
        sa.Column("provider", sa.String(length=80), nullable=True),
        sa.Column("account_last4", sa.String(length=4), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("net = GREATEST(gross - deductions, 0)", name=op.f("ck_payslips_net")),
        sa.CheckConstraint(
            "net >= 0 AND gross >= 0 AND deductions >= 0 AND carried_forward >= 0",
            name=op.f("ck_payslips_amounts"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "employee_id"],
            ["employees.tenant_id", "employees.id"],
            name=op.f("fk_payslips_tenant_id_employee_id_employees"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "run_id"],
            ["payroll_runs.tenant_id", "payroll_runs.id"],
            name=op.f("fk_payslips_tenant_id_run_id_payroll_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payslips")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_payslips_tenant_id_id")),
        sa.UniqueConstraint(
            "tenant_id", "run_id", "employee_id", name=op.f("uq_payslips_tenant_id_run_id_employee_id")
        ),
    )
    op.create_index("ix_payslips_employee", "payslips", ["tenant_id", "employee_id"], unique=False)
    op.create_index(op.f("ix_payslips_tenant_id"), "payslips", ["tenant_id"], unique=False)
    op.create_table(
        "salary_structures",
        sa.Column("employee_id", sa.Uuid(), nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column("pay_rule", sa.String(length=10), nullable=False),
        sa.Column("basic", sa.BigInteger(), nullable=False),
        sa.Column("house_rent", sa.BigInteger(), nullable=False),
        sa.Column("medical", sa.BigInteger(), nullable=False),
        sa.Column("conveyance", sa.BigInteger(), nullable=False),
        sa.Column("other", sa.BigInteger(), nullable=False),
        sa.Column("rate", sa.BigInteger(), nullable=False),
        sa.Column("overtime", sa.Boolean(), nullable=False),
        sa.Column("deduct_tax", sa.Boolean(), nullable=False),
        sa.Column("tax_free_override", sa.BigInteger(), nullable=True),
        sa.Column("payment_method", sa.String(length=8), nullable=False),
        sa.Column("provider", sa.String(length=80), nullable=True),
        sa.Column("account_enc", sa.String(length=300), nullable=True),
        sa.Column("account_last4", sa.String(length=4), nullable=True),
        sa.Column("note", sa.String(length=300), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "pay_rule IN ('monthly', 'hourly', 'daily')", name=op.f("ck_salary_structures_pay_rule")
        ),
        sa.CheckConstraint(
            "payment_method IN ('cash', 'bank', 'wallet')", name=op.f("ck_salary_structures_payment_method")
        ),
        sa.CheckConstraint(
            "basic >= 0 AND house_rent >= 0 AND medical >= 0 AND conveyance >= 0 AND other >= 0 AND rate >= 0",
            name=op.f("ck_salary_structures_amounts"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_salary_structures_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "employee_id"],
            ["employees.tenant_id", "employees.id"],
            name=op.f("fk_salary_structures_tenant_id_employee_id_employees"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_salary_structures")),
        sa.UniqueConstraint(
            "tenant_id",
            "employee_id",
            "effective_from",
            name=op.f("uq_salary_structures_tenant_id_employee_id_effective_from"),
        ),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_salary_structures_tenant_id_id")),
    )
    op.create_index(op.f("ix_salary_structures_tenant_id"), "salary_structures", ["tenant_id"], unique=False)
    # ### end Alembic commands ###
    for table in (
        "payroll_settings",
        "salary_structures",
        "payroll_loans",
        "payroll_runs",
        "payslips",
        "payroll_items",
    ):
        rls.tenant_table(table)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_salary_structures_tenant_id"), table_name="salary_structures")
    op.drop_table("salary_structures")
    op.drop_index(op.f("ix_payslips_tenant_id"), table_name="payslips")
    op.drop_index("ix_payslips_employee", table_name="payslips")
    op.drop_table("payslips")
    op.drop_index(op.f("ix_payroll_loans_tenant_id"), table_name="payroll_loans")
    op.drop_index("ix_payroll_loans_employee", table_name="payroll_loans")
    op.drop_table("payroll_loans")
    op.drop_index(op.f("ix_payroll_items_tenant_id"), table_name="payroll_items")
    op.drop_index("ix_payroll_items_run", table_name="payroll_items")
    op.drop_table("payroll_items")
    op.drop_index(op.f("ix_payroll_runs_tenant_id"), table_name="payroll_runs")
    op.drop_table("payroll_runs")
    op.drop_table("payroll_settings")
    # ### end Alembic commands ###
