"""data rights: deletion grace period, admin two-step policy, audit retention anchors

Revision ID: 0005
Revises: 0004
Create Date: 2026-10-01 01:51:15.428654
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from migrations import rls

revision: str = "0005"
down_revision: str | None = "0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_anchors",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("seq", sa.BigInteger(), nullable=False),
        sa.Column("hash", sa.String(length=64), nullable=False),
        sa.Column("purged_rows", sa.BigInteger(), nullable=False),
        sa.Column("purged_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_anchors")),
        sa.UniqueConstraint("tenant_id", "seq", name=op.f("uq_audit_anchors_tenant_id_seq")),
    )
    op.create_index(op.f("ix_audit_anchors_tenant_id"), "audit_anchors", ["tenant_id"], unique=False)
    op.add_column("tenants", sa.Column("deletion_contact", sa.String(length=254), nullable=True))
    op.add_column(
        "tenants", sa.Column("require_admin_mfa", sa.Boolean(), server_default="false", nullable=False)
    )
    # ### end Alembic commands ###
    # The app reads anchors to verify the chain; only the maintenance job (owner) writes them.
    rls.tenant_table("audit_anchors", privileges="SELECT")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tenants", "require_admin_mfa")
    op.drop_column("tenants", "deletion_contact")
    op.drop_index(op.f("ix_audit_anchors_tenant_id"), table_name="audit_anchors")
    op.drop_table("audit_anchors")
    # ### end Alembic commands ###
