"""onboarding checklists: templates, runs, and tasks that belong to a run or a document

Revision ID: 0012
Revises: 0011
Create Date: 2026-10-01 11:41:42.550813
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from migrations import rls

revision: str = "0012"
down_revision: str | None = "0011"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "onboarding_templates",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("automatic", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("items", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_onboarding_templates_created_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_onboarding_templates")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_onboarding_templates_tenant_id_id")),
    )
    op.create_index(
        op.f("ix_onboarding_templates_tenant_id"), "onboarding_templates", ["tenant_id"], unique=False
    )
    op.create_table(
        "onboarding_runs",
        sa.Column("employee_id", sa.Uuid(), nullable=False),
        sa.Column("template_name", sa.String(length=120), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("started_by", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["started_by"], ["users.id"], name=op.f("fk_onboarding_runs_started_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "employee_id"],
            ["employees.tenant_id", "employees.id"],
            name=op.f("fk_onboarding_runs_tenant_id_employee_id_employees"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_onboarding_runs")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_onboarding_runs_tenant_id_id")),
    )
    op.create_index(
        "ix_onboarding_runs_employee", "onboarding_runs", ["tenant_id", "employee_id"], unique=False
    )
    op.create_index(op.f("ix_onboarding_runs_tenant_id"), "onboarding_runs", ["tenant_id"], unique=False)
    op.add_column("tasks", sa.Column("onboarding_run_id", sa.Uuid(), nullable=True))
    op.add_column("tasks", sa.Column("document_id", sa.Uuid(), nullable=True))
    op.create_foreign_key(
        op.f("fk_tasks_tenant_id_onboarding_run_id_onboarding_runs"),
        "tasks",
        "onboarding_runs",
        ["tenant_id", "onboarding_run_id"],
        ["tenant_id", "id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
    rls.tenant_table("onboarding_templates")
    rls.tenant_table("onboarding_runs")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_tasks_tenant_id_onboarding_run_id_onboarding_runs"), "tasks", type_="foreignkey"
    )
    op.drop_column("tasks", "document_id")
    op.drop_column("tasks", "onboarding_run_id")
    op.drop_index(op.f("ix_onboarding_runs_tenant_id"), table_name="onboarding_runs")
    op.drop_index("ix_onboarding_runs_employee", table_name="onboarding_runs")
    op.drop_table("onboarding_runs")
    op.drop_index(op.f("ix_onboarding_templates_tenant_id"), table_name="onboarding_templates")
    op.drop_table("onboarding_templates")
    # ### end Alembic commands ###
