"""tasks and projects: projects with members, tasks on a board, checklists and comments

Revision ID: 0009
Revises: 0008
Create Date: 2026-10-01 06:47:08.104216
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from migrations import rls

revision: str = "0009"
down_revision: str | None = "0008"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "projects",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("department_id", sa.Uuid(), nullable=True),
        sa.Column("member_ids", sa.ARRAY(sa.Uuid()), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("color", sa.String(length=7), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint("color ~ '^#[0-9a-fA-F]{6}$'", name=op.f("ck_projects_color")),
        sa.CheckConstraint("status IN ('active', 'archived')", name=op.f("ck_projects_status")),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], name=op.f("fk_projects_created_by_users")),
        sa.ForeignKeyConstraint(
            ["tenant_id", "department_id"],
            ["departments.tenant_id", "departments.id"],
            name=op.f("fk_projects_tenant_id_department_id_departments"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_projects")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_projects_tenant_id_id")),
    )
    op.create_index("ix_projects_status", "projects", ["tenant_id", "status"], unique=False)
    op.create_index(op.f("ix_projects_tenant_id"), "projects", ["tenant_id"], unique=False)
    op.create_table(
        "tasks",
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("priority", sa.String(length=10), nullable=False),
        sa.Column("assignee_id", sa.Uuid(), nullable=True),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("position", sa.Float(), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("source", sa.String(length=40), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint("(status = 'done') = (completed_at IS NOT NULL)", name=op.f("ck_tasks_completed")),
        sa.CheckConstraint("priority IN ('low', 'normal', 'high', 'urgent')", name=op.f("ck_tasks_priority")),
        sa.CheckConstraint("status IN ('todo', 'doing', 'done')", name=op.f("ck_tasks_status")),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], name=op.f("fk_tasks_created_by_users")),
        sa.ForeignKeyConstraint(
            ["tenant_id", "assignee_id"],
            ["employees.tenant_id", "employees.id"],
            name=op.f("fk_tasks_tenant_id_assignee_id_employees"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "project_id"],
            ["projects.tenant_id", "projects.id"],
            name=op.f("fk_tasks_tenant_id_project_id_projects"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tasks")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_tasks_tenant_id_id")),
    )
    op.create_index(
        "ix_tasks_assignee", "tasks", ["tenant_id", "assignee_id", "status", "due_date"], unique=False
    )
    op.create_index(
        "ix_tasks_project", "tasks", ["tenant_id", "project_id", "status", "position"], unique=False
    )
    op.create_index(op.f("ix_tasks_tenant_id"), "tasks", ["tenant_id"], unique=False)
    op.create_table(
        "task_checklist_items",
        sa.Column("task_id", sa.Uuid(), nullable=False),
        sa.Column("text", sa.String(length=300), nullable=False),
        sa.Column("done", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("position", sa.Float(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "task_id"],
            ["tasks.tenant_id", "tasks.id"],
            name=op.f("fk_task_checklist_items_tenant_id_task_id_tasks"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_task_checklist_items")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_task_checklist_items_tenant_id_id")),
    )
    op.create_index(
        op.f("ix_task_checklist_items_tenant_id"), "task_checklist_items", ["tenant_id"], unique=False
    )
    op.create_index(
        "ix_task_checklist_task", "task_checklist_items", ["tenant_id", "task_id", "position"], unique=False
    )
    op.create_table(
        "task_comments",
        sa.Column("task_id", sa.Uuid(), nullable=False),
        sa.Column("author_id", sa.Uuid(), nullable=True),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["author_id"], ["users.id"], name=op.f("fk_task_comments_author_id_users")),
        sa.ForeignKeyConstraint(
            ["tenant_id", "task_id"],
            ["tasks.tenant_id", "tasks.id"],
            name=op.f("fk_task_comments_tenant_id_task_id_tasks"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_task_comments")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_task_comments_tenant_id_id")),
    )
    op.create_index(
        "ix_task_comments_task", "task_comments", ["tenant_id", "task_id", "created_at"], unique=False
    )
    op.create_index(op.f("ix_task_comments_tenant_id"), "task_comments", ["tenant_id"], unique=False)
    # ### end Alembic commands ###
    for table in ("projects", "tasks", "task_checklist_items", "task_comments"):
        rls.tenant_table(table)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_task_comments_tenant_id"), table_name="task_comments")
    op.drop_index("ix_task_comments_task", table_name="task_comments")
    op.drop_table("task_comments")
    op.drop_index("ix_task_checklist_task", table_name="task_checklist_items")
    op.drop_index(op.f("ix_task_checklist_items_tenant_id"), table_name="task_checklist_items")
    op.drop_table("task_checklist_items")
    op.drop_index(op.f("ix_tasks_tenant_id"), table_name="tasks")
    op.drop_index("ix_tasks_project", table_name="tasks")
    op.drop_index("ix_tasks_assignee", table_name="tasks")
    op.drop_table("tasks")
    op.drop_index(op.f("ix_projects_tenant_id"), table_name="projects")
    op.drop_index("ix_projects_status", table_name="projects")
    op.drop_table("projects")
    # ### end Alembic commands ###
