"""documents and policies: files with versions, visibility and acknowledgements

Revision ID: 0011
Revises: 0010
Create Date: 2026-10-01 11:02:38.867158
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from migrations import rls

revision: str = "0011"
down_revision: str | None = "0010"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "documents",
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("category", sa.String(length=12), nullable=False),
        sa.Column("visibility", sa.String(length=12), nullable=False),
        sa.Column("visibility_ids", postgresql.ARRAY(sa.Uuid()), nullable=False),
        sa.Column("requires_ack", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("current_version_id", sa.Uuid(), nullable=True),
        sa.Column("archived", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "category IN ('policy', 'handbook', 'sop', 'form', 'other')", name=op.f("ck_documents_category")
        ),
        sa.CheckConstraint(
            "visibility = 'everyone' OR cardinality(visibility_ids) > 0",
            name=op.f("ck_documents_visibility_ids"),
        ),
        sa.CheckConstraint(
            "visibility IN ('everyone', 'roles', 'departments')", name=op.f("ck_documents_visibility")
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], name=op.f("fk_documents_created_by_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_documents")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_documents_tenant_id_id")),
    )
    op.create_index("ix_documents_list", "documents", ["tenant_id", "archived", "category"], unique=False)
    op.create_index(op.f("ix_documents_tenant_id"), "documents", ["tenant_id"], unique=False)
    op.create_table(
        "document_versions",
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("filename", sa.String(length=200), nullable=False),
        sa.Column("content_type", sa.String(length=100), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("data", sa.LargeBinary(), nullable=True),
        sa.Column("note", sa.String(length=500), nullable=True),
        sa.Column("uploaded_by", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("size > 0", name=op.f("ck_document_versions_size")),
        sa.ForeignKeyConstraint(
            ["tenant_id", "document_id"],
            ["documents.tenant_id", "documents.id"],
            name=op.f("fk_document_versions_tenant_id_document_id_documents"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by"], ["users.id"], name=op.f("fk_document_versions_uploaded_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_versions")),
        sa.UniqueConstraint("document_id", "number", name=op.f("uq_document_versions_document_id_number")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_document_versions_tenant_id_id")),
    )
    op.create_index(op.f("ix_document_versions_tenant_id"), "document_versions", ["tenant_id"], unique=False)
    op.create_table(
        "document_acks",
        sa.Column("version_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("acked_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "version_id"],
            ["document_versions.tenant_id", "document_versions.id"],
            name=op.f("fk_document_acks_tenant_id_version_id_document_versions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_document_acks_user_id_users")),
        sa.PrimaryKeyConstraint("version_id", "user_id", name=op.f("pk_document_acks")),
    )
    op.create_index(op.f("ix_document_acks_tenant_id"), "document_acks", ["tenant_id"], unique=False)
    op.create_index("ix_document_acks_user", "document_acks", ["tenant_id", "user_id"], unique=False)
    # ### end Alembic commands ###
    rls.tenant_table("documents")
    # Versions are never edited once uploaded; they go with their document.
    rls.tenant_table("document_versions", privileges="SELECT, INSERT, DELETE")
    rls.tenant_table("document_acks", privileges="SELECT, INSERT, DELETE")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_document_acks_user", table_name="document_acks")
    op.drop_index(op.f("ix_document_acks_tenant_id"), table_name="document_acks")
    op.drop_table("document_acks")
    op.drop_index(op.f("ix_document_versions_tenant_id"), table_name="document_versions")
    op.drop_table("document_versions")
    op.drop_index(op.f("ix_documents_tenant_id"), table_name="documents")
    op.drop_index("ix_documents_list", table_name="documents")
    op.drop_table("documents")
    # ### end Alembic commands ###
