"""document passages: searchable text of each document's current version

Revision ID: 0016
Revises: 0015
Create Date: 2026-10-04 21:48:21.682804
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from migrations import rls

revision: str = "0016"
down_revision: str | None = "0015"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "document_passages",
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("version_id", sa.Uuid(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column(
            "search",
            postgresql.TSVECTOR(),
            sa.Computed("to_tsvector('simple', text)", persisted=True),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "document_id"],
            ["documents.tenant_id", "documents.id"],
            name=op.f("fk_document_passages_tenant_id_document_id_documents"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_passages")),
    )
    op.create_index(
        "ix_document_passages_document", "document_passages", ["tenant_id", "document_id"], unique=False
    )
    op.create_index(
        "ix_document_passages_search", "document_passages", ["search"], unique=False, postgresql_using="gin"
    )
    op.create_index(op.f("ix_document_passages_tenant_id"), "document_passages", ["tenant_id"], unique=False)
    # ### end Alembic commands ###
    rls.tenant_table("document_passages")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_document_passages_tenant_id"), table_name="document_passages")
    op.drop_index("ix_document_passages_search", table_name="document_passages", postgresql_using="gin")
    op.drop_index("ix_document_passages_document", table_name="document_passages")
    op.drop_table("document_passages")
    # ### end Alembic commands ###
